language: python
python:
- '2.7'
- '3.5'
- '3.6'
- pypy
install:
- pip install -r requirements.txt
- pip install tox-travis
script:
- tox
deploy:
  provider: pypi
  skip_existing: true
  on:
    tags: true
  user: andreferreirav2
  password:
    secure: HNExGGGfuqiH+yqWJelfuimN8ZF1ip2hgoPo/1feZM/ErEVcl+Iu+/QM03wghfNDt8PAWQxBYlXpLSbQuEB7JFk8u0NA0ZyTlk9XLYMswamI7hX+MTOeYpcNDYDHfLJy31SiDAu7xr0D2W+ehw7XI7Bj7f/ABrWnNoHNa97Bj/AiDCkWpjLnfH30DhHG1Xo/stQ0b4SZsuMP2oKZLAIKaAya7eTFpUzbPovSWRjwNqRNWmbSGj6NXFFYjWNDOVssY+qTPoi0Ge9xiac6PRVgXYSaXCdTHdArv3AHtX4wFqBIFebbw5J9xxRFgSfE5CGlRR+MeTbSSBzeDQN0SWLf0jeQa1927cHf0MXtCrcgA0eCHxROxS2VH83vrNahLurxtW3AikAZxgBlD1t2TTTrFsZB4U6Wgz+pGQ3ek3FK6gPH+vz4BVeZwEjttrt9+WNU48LdHV7bJsFcO23BiJMHu9D8VANcd/unMEHx3AUNTLBIjYLtSApmlN53rUiDTH/9at2NMZnEC8S/95zykTROHMhCAo1eTwPBTzzJqIUSG6ZTuCimVS0F4LikkyoCqeWaB1/hyZ0WOl0XdXpZzMUGgoctMvid/YdmgTVVkog/TEMHI8kNjbDwpRv68V0nQhg9nc8rKGJ7kfPN6Q2QtjDNHOjG3An+RhaVk4lTOzge2cY=
